baseurl = "http://zeraxxus.dk/"
title = "www.zeraxxus.dk"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Bjarne Kristensen"
googleAnalytics = "XXX"
disqusShortname = "zeraxxus"

[Author]
    name = "Bjarne Kristensen"
    profile = "https://plus.google.com/115860921316607758048"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Bjarne \"Zeraxxus\" Kristensen"
    description = "Personal Blog"
    github = "https://github.com/zeraxxus"
    linkedin = "https://linkedin.com/in/bjarne-kristensen-06b38b104"
    gplus = "https://plus.google.com/115860921316607758048"
    twitter = "https://twitter.com/Zeraxxus"
    stackoverflow = "http://stackoverflow.com/users/876238/zeraxxus"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4