baseurl = "http://www.pixelpowered.eu/"
title = "PixelPowered"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Bjarne Kristensen"
googleAnalytics = "XXX"
disqusShortname = "XXX"

[Author]
    name = "Bjarne Kristensen"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "PixelPowered"
    description = "Game Development"
    github = "https://github.com/XXX"
    linkedin = "https://linkedin.com/in/XXX/"
    gplus = "https://google.com/+XXX"
    twitter = "https://twitter.com/XXX"
    stackoverflow = "http://stackoverflow.com/users/XXX/YYY"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4